### ISSUE TITLE
no circles found

### ISSUE THREAD

**Issue by zchrissirhcz** [kevinhughes27/circleDetector#1]
I downloaded your repo and run the code, with the image included in the repo and alse set bothe canny_threshold and circle_threshold alter from 1 to 200, but no circles could be found.

Could you please provide a proper pamameter which can detect circles?  Or is your code still not completely implemented?

**Comment by kevinhughes27** [comment]
I wrote this code for a school assignment several years ago - its not intended as production code or anything but more educational if someone wants to see how RANSAC works.

I pulled up the write up from the assignment, try something along the lines of:
thresh: 150 - 200
circle_thresh: 50
iterations: 1000.

You can also try setting the debug flag to false in the code and displaying the images after each step. 

If you like I can send you my assignment write up as well. I am going to close this issue though since I don't intend to work on this anymore. If you find any bugs I'd love to hear about them still.
